encoding: utf-8

# 首页使用下面的命令生成
#!/bin/bash
# find **/*.md |sed 's/^\(.*\)\/\(.*\)\.md/- [\2](\1\/\2.md)/' > index.md

# SEO相关信息
title: Asins Blog
description: 简单其实不简单
keywords: Asins,Blog,Html,JavaScript,Vue
author: Asins
footerText: '©Asins 2020'

# 域名配置
# baseUrl配置,如果网站部署在根目录下的目录中，请设置为 /目录名
domainUrl: 'https://blog.nootn.com'

theme: jekyll-theme-dinky

